### ISSUE TITLE
Do not use limit if request for personal projects list (or it fails with 504 after a lot of time of waiting)

### ISSUE THREAD

**Issue by ghost** [Asana/python-asana#25]
list(client.projects.find_by_workspace(498346170860, {})) # list of personal projects
do not work

reason: need to do not include limit, with limit (any number, 0, 100, 1000) it will return 504

```
Traceback (most recent call last):
 File "/Users/lorddaedra/Projects/asankadesk/manage.py", line 10, in <module>
 execute_from_command_line(sys.argv)
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
 utility.execute()
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
 self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
 self.execute(*args, **cmd_options)
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
 output = self.handle(*args, **options)
 File "/Users/lorddaedra/Projects/asankadesk/asankadeskbase/management/commands/sync_user_with_asana.py", line 35, in handle
 user.sync_projects(client)
 File "/Users/lorddaedra/Projects/asankadesk/asankadeskbase/models.py", line 99, in sync_projects
 personal_projects_asana = list(client.projects.find_by_workspace(498346170860, {}))
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/page_iterator.py", line 58, in items
 for page in self:
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/page_iterator.py", line 40, in __next__
 result = self.get_initial()
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/page_iterator.py", line 70, in get_initial
 return self.client.get(self.path, self.query, **self.options)
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/client.py", line 106, in get
 return self.request('get', path, params=query, **options)
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/client.py", line 90, in request
 raise e
 File "/Users/lorddaedra/.pyenv/versions/asanka/lib/python3.5/site-packages/asana/client.py", line 79, in request
 raise error.ServerError(response)
asana.error.ServerError: Server Error

```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182692189208479/182694765039198)

**Comment by lorddaedra** [comment]
PS. Asana devs: Singletons are bad practice, antipattern in most cases.

You use 1 single id for all "organizations", which contains personal projects.

**Comment by lorddaedra** [comment]
Also check Asana support Case 253473
